spring.application.name=ExpenseTracker
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/expense_tracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ERciGLcWbVtGmiEiPgzbhwFIuNHkPipn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
